// Auto-generated Gallery Data
export interface GalleryItem {
  id: string;
  fileName: string;
  title: string;
  folderId: string;
  folderName: string;
  src: string;
  badge: string;
  fileType: 'image' | 'gif' | 'video';
  isFromFull: boolean;
}

export interface GalleryFolder {
  id: string;
  name: string;
  description: string;
  count: number;
  previewSrc: string;
}

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    "id": "how-to-enter-it-horizontal_jpg",
    "fileName": "how-to-enter-it-horizontal.jpg",
    "title": "Как войти в IT (YouTube 16:9)",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/how-to-enter-it-horizontal.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": false
  },
  {
    "id": "how-to-enter-it-vertical_png",
    "fileName": "how-to-enter-it-vertical.png",
    "title": "Как войти в IT (Reels 9:16)",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/how-to-enter-it-vertical.png",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": false
  },
  {
    "id": "mrdev-bracket-logo_jpg",
    "fileName": "mrdev-bracket-logo.jpg",
    "title": "Логотип MrDEV Bracket",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/mrdev-bracket-logo.jpg",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": false
  },
  {
    "id": "mrdev-mascot-portrait_jpg",
    "fileName": "mrdev-mascot-portrait.jpg",
    "title": "Портрет маскота MrDev",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/mrdev-mascot-portrait.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": false
  },
  {
    "id": "mrdev-eyes-banner_jpg",
    "fileName": "mrdev-eyes-banner.jpg",
    "title": "Баннер взгляда Mr Developer",
    "folderId": "banners",
    "folderName": "Баннеры и шапки",
    "src": "gallery/mrdev-eyes-banner.jpg",
    "badge": "Баннер",
    "fileType": "image",
    "isFromFull": false
  },
  {
    "id": "mrdev-mascot-hoodie_jpg",
    "fileName": "mrdev-mascot-hoodie.jpg",
    "title": "Маскот Mr Developer в худи",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/mrdev-mascot-hoodie.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": false
  },
  {
    "id": "chatgpt_image_1_______2026_____11_55_06__1__png",
    "fileName": "ChatGPT Image 1 сент. 2026 г., 11_55_06 (1).png",
    "title": "ChatGPT Image 1 сент. 2026 г., 11 55 06 (1)",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%201%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2011_55_06%20(1).png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_1_______2026_____11_55_06__2__png",
    "fileName": "ChatGPT Image 1 сент. 2026 г., 11_55_06 (2).png",
    "title": "ChatGPT Image 1 сент. 2026 г., 11 55 06 (2)",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%201%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2011_55_06%20(2).png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_1_______2026_____11_57_34_png",
    "fileName": "ChatGPT Image 1 сент. 2026 г., 11_57_34.png",
    "title": "ChatGPT Image 1 сент. 2026 г., 11 57 34",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%201%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2011_57_34.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_1_______2026_____11_59_21_png",
    "fileName": "ChatGPT Image 1 сент. 2026 г., 11_59_21.png",
    "title": "ChatGPT Image 1 сент. 2026 г., 11 59 21",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%201%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2011_59_21.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_14_______2026_____17_36_40_png",
    "fileName": "ChatGPT Image 14 сент. 2026 г., 17_36_40.png",
    "title": "ChatGPT Image 14 сент. 2026 г., 17 36 40",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2014%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2017_36_40.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_14_______2026_____17_39_05_png",
    "fileName": "ChatGPT Image 14 сент. 2026 г., 17_39_05.png",
    "title": "ChatGPT Image 14 сент. 2026 г., 17 39 05",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2014%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2017_39_05.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_18______2026_____15_57_44_png",
    "fileName": "ChatGPT Image 18 авг. 2026 г., 15_57_44.png",
    "title": "ChatGPT Image 18 авг. 2026 г., 15 57 44",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2018%20%D0%B0%D0%B2%D0%B3.%202026%20%D0%B3.%2C%2015_57_44.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_2_______2026_____15_38_05_png",
    "fileName": "ChatGPT Image 2 сент. 2026 г., 15_38_05.png",
    "title": "ChatGPT Image 2 сент. 2026 г., 15 38 05",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%202%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2015_38_05.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_2_______2026_____15_41_25_png",
    "fileName": "ChatGPT Image 2 сент. 2026 г., 15_41_25.png",
    "title": "ChatGPT Image 2 сент. 2026 г., 15 41 25",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%202%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2015_41_25.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_2_______2026_____15_43_06_png",
    "fileName": "ChatGPT Image 2 сент. 2026 г., 15_43_06.png",
    "title": "ChatGPT Image 2 сент. 2026 г., 15 43 06",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%202%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2015_43_06.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_2_______2026_____15_44_24_png",
    "fileName": "ChatGPT Image 2 сент. 2026 г., 15_44_24.png",
    "title": "ChatGPT Image 2 сент. 2026 г., 15 44 24",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%202%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2015_44_24.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_28______2026_____16_42_57_png",
    "fileName": "ChatGPT Image 28 авг. 2026 г., 16_42_57.png",
    "title": "ChatGPT Image 28 авг. 2026 г., 16 42 57",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2028%20%D0%B0%D0%B2%D0%B3.%202026%20%D0%B3.%2C%2016_42_57.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_28______2026_____16_44_40_png",
    "fileName": "ChatGPT Image 28 авг. 2026 г., 16_44_40.png",
    "title": "ChatGPT Image 28 авг. 2026 г., 16 44 40",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2028%20%D0%B0%D0%B2%D0%B3.%202026%20%D0%B3.%2C%2016_44_40.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_31______2026_____15_41_11__1__png",
    "fileName": "ChatGPT Image 31 авг. 2026 г., 15_41_11 (1).png",
    "title": "ChatGPT Image 31 авг. 2026 г., 15 41 11 (1)",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2031%20%D0%B0%D0%B2%D0%B3.%202026%20%D0%B3.%2C%2015_41_11%20(1).png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_31______2026_____15_46_02_png",
    "fileName": "ChatGPT Image 31 авг. 2026 г., 15_46_02.png",
    "title": "ChatGPT Image 31 авг. 2026 г., 15 46 02",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%2031%20%D0%B0%D0%B2%D0%B3.%202026%20%D0%B3.%2C%2015_46_02.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "chatgpt_image_4_______2026_____13_28_28_png",
    "fileName": "ChatGPT Image 4 сент. 2026 г., 13_28_28.png",
    "title": "ChatGPT Image 4 сент. 2026 г., 13 28 28",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/ChatGPT%20Image%204%20%D1%81%D0%B5%D0%BD%D1%82.%202026%20%D0%B3.%2C%2013_28_28.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "courses_live_full_png",
    "fileName": "courses_live_full.png",
    "title": "Courses live full",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/courses_live_full.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "fbacc7d0-56db-4f90-8701-e8da76183251_png",
    "fileName": "fbacc7d0-56db-4f90-8701-e8da76183251.png",
    "title": "Fbacc7d0 56db 4f90 8701 e8da76183251",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/fbacc7d0-56db-4f90-8701-e8da76183251.png",
    "badge": "PNG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "images__1__jpg",
    "fileName": "images (1).jpg",
    "title": "Images (1)",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/images%20(1).jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "images_jpg",
    "fileName": "images.jpg",
    "title": "Images",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/images.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "mr_developer_-_courses_preview_png",
    "fileName": "Mr Developer - courses preview.png",
    "title": "Mr Developer   courses preview",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/Mr%20Developer%20-%20courses%20preview.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "mr_developer_business_model_png",
    "fileName": "MR_Developer_business_model.png",
    "title": "Business model",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/MR_Developer_business_model.png",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "mr_developer_channel_banner_jpg",
    "fileName": "mr_developer_channel_banner.jpg",
    "title": "Channel banner",
    "folderId": "banners",
    "folderName": "Баннеры и шапки",
    "src": "gallery/full/mr_developer_channel_banner.jpg",
    "badge": "Баннер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "mr_developer_channel_banner_clean_1788422660113_jpg",
    "fileName": "mr_developer_channel_banner_clean_1788422660113.jpg",
    "title": "Channel banner clean",
    "folderId": "banners",
    "folderName": "Баннеры и шапки",
    "src": "gallery/full/mr_developer_channel_banner_clean_1788422660113.jpg",
    "badge": "Баннер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "mr_developer_official_avatar_jpg",
    "fileName": "mr_developer_official_avatar.jpg",
    "title": "Official avatar",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/mr_developer_official_avatar.jpg",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "mr_dev_yt_preview_1789389184038_jpg",
    "fileName": "mr_dev_yt_preview_1789389184038.jpg",
    "title": "Yt preview",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/mr_dev_yt_preview_1789389184038.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "pose_1_coding_flow_1788265791557_jpg",
    "fileName": "pose_1_coding_flow_1788265791557.jpg",
    "title": "Pose 1 coding flow",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/pose_1_coding_flow_1788265791557.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "pose_2_explaining_jpg",
    "fileName": "pose_2_explaining.jpg",
    "title": "Pose 2 explaining",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/pose_2_explaining.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_1_jpg",
    "fileName": "Ryo 1.jpg",
    "title": "Ryo 1",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%201.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_2_jpg",
    "fileName": "Ryo 2.jpg",
    "title": "Ryo 2",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%202.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_3_jpg",
    "fileName": "Ryo 3.jpg",
    "title": "Ryo 3",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%203.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_4_jpg",
    "fileName": "Ryo 4.jpg",
    "title": "Ryo 4",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%204.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yamada_jpg",
    "fileName": "Ryo Yamada.jpg",
    "title": "Ryo Yamada",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%20Yamada.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yamada_png",
    "fileName": "Ryo Yamada.png",
    "title": "Ryo Yamada",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%20Yamada.png",
    "badge": "PNG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yamada1_jpg",
    "fileName": "Ryo Yamada1.jpg",
    "title": "Ryo Yamada1",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo%20Yamada1.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo-avatar_jpg",
    "fileName": "Ryo-avatar.jpg",
    "title": "Ryo avatar",
    "folderId": "brand",
    "folderName": "Бренд и концепты",
    "src": "gallery/full/Ryo-avatar.jpg",
    "badge": "Бренд",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_jpg",
    "fileName": "Ryo.jpg",
    "title": "Ryo",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/Ryo.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_clean_no_cyan_jpg",
    "fileName": "ryo_clean_no_cyan.jpg",
    "title": "Clean no cyan",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/ryo_clean_no_cyan.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_flow_exact_style_jpg",
    "fileName": "ryo_flow_exact_style.jpg",
    "title": "Flow exact style",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/ryo_flow_exact_style.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_gif_1_gif",
    "fileName": "ryo_gif_1.gif",
    "title": "Gif 1",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/ryo_gif_1.gif",
    "badge": "GIF Loop",
    "fileType": "gif",
    "isFromFull": true
  },
  {
    "id": "ryo_gif_2_gif",
    "fileName": "ryo_gif_2.gif",
    "title": "Gif 2",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/ryo_gif_2.gif",
    "badge": "GIF Loop",
    "fileType": "gif",
    "isFromFull": true
  },
  {
    "id": "ryo_gif_3_gif",
    "fileName": "ryo_gif_3.gif",
    "title": "Gif 3",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/ryo_gif_3.gif",
    "badge": "GIF Loop",
    "fileType": "gif",
    "isFromFull": true
  },
  {
    "id": "ryo_gif_4_gif",
    "fileName": "ryo_gif_4.gif",
    "title": "Gif 4",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/ryo_gif_4.gif",
    "badge": "GIF Loop",
    "fileType": "gif",
    "isFromFull": true
  },
  {
    "id": "ryo_hand_touching_cheek_1789666084137_jpg",
    "fileName": "ryo_hand_touching_cheek_1789666084137.jpg",
    "title": "Hand touching cheek",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_hand_touching_cheek_1789666084137.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_masterpiece_hands_blush_1788284900090_jpg",
    "fileName": "ryo_masterpiece_hands_blush_1788284900090.jpg",
    "title": "Masterpiece hands blush",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_masterpiece_hands_blush_1788284900090.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_masterpiece_hands_on_cheeks_jpg",
    "fileName": "ryo_masterpiece_hands_on_cheeks.jpg",
    "title": "Masterpiece hands on cheeks",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_masterpiece_hands_on_cheeks.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_masterpiece_hand_on_chin_jpg",
    "fileName": "ryo_masterpiece_hand_on_chin.jpg",
    "title": "Masterpiece hand on chin",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_masterpiece_hand_on_chin.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_matte_mrdev_1791266246579_jpg",
    "fileName": "ryo_matte_mrdev_1791266246579.jpg",
    "title": "Matte mrdev",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/ryo_matte_mrdev_1791266246579.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_mr_developer_1791264756492_________jpg",
    "fileName": "ryo_mr_developer_1791264756492 — копия.jpg",
    "title": "Mr developer — копия",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/ryo_mr_developer_1791264756492%20%E2%80%94%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_mr_developer_banner_1791265942920_jpg",
    "fileName": "ryo_mr_developer_banner_1791265942920.jpg",
    "title": "Banner",
    "folderId": "banners",
    "folderName": "Баннеры и шапки",
    "src": "gallery/full/ryo_mr_developer_banner_1791265942920.jpg",
    "badge": "Баннер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_phase_notice_1789666821505_jpg",
    "fileName": "ryo_phase_notice_1789666821505.jpg",
    "title": "Phase notice",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/ryo_phase_notice_1789666821505.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_pose_01_joy_jpg",
    "fileName": "ryo_pose_01_joy.jpg",
    "title": "Поза: 01 joy",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_pose_01_joy.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_pose_02_sad_jpg",
    "fileName": "ryo_pose_02_sad.jpg",
    "title": "Поза: 02 sad",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_pose_02_sad.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_pose_03_coding_jpg",
    "fileName": "ryo_pose_03_coding.jpg",
    "title": "Поза: 03 coding",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_pose_03_coding.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_pose_04_thinking_jpg",
    "fileName": "ryo_pose_04_thinking.jpg",
    "title": "Поза: 04 thinking",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_pose_04_thinking.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_scene_01_bored_jpg",
    "fileName": "ryo_scene_01_bored.jpg",
    "title": "Сцена: 01 bored",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_scene_01_bored.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_scene_02_noticed_jpg",
    "fileName": "ryo_scene_02_noticed.jpg",
    "title": "Сцена: 02 noticed",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_scene_02_noticed.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_scene_03_flustered_jpg",
    "fileName": "ryo_scene_03_flustered.jpg",
    "title": "Сцена: 03 flustered",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_scene_03_flustered.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_scene_04_cover_face_jpg",
    "fileName": "ryo_scene_04_cover_face.jpg",
    "title": "Сцена: 04 cover face",
    "folderId": "poses",
    "folderName": "Позы и сцены Ryo",
    "src": "gallery/full/ryo_scene_04_cover_face.jpg",
    "badge": "Сцена",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_shy_girl_full_cycle_compact_gif",
    "fileName": "ryo_shy_girl_full_cycle_compact.gif",
    "title": "Shy girl full cycle compact",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/ryo_shy_girl_full_cycle_compact.gif",
    "badge": "GIF Loop",
    "fileType": "gif",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_01_wink_1788279355633_jpg",
    "fileName": "ryo_sticker_01_wink_1788279355633.jpg",
    "title": "Стикер: 01 wink",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_01_wink_1788279355633.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_02_confident_jpg",
    "fileName": "ryo_sticker_02_confident.jpg",
    "title": "Стикер: 02 confident",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_02_confident.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_03_clean_shock_jpg",
    "fileName": "ryo_sticker_03_clean_shock.jpg",
    "title": "Стикер: 03 clean shock",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_03_clean_shock.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_04_coffee_jpg",
    "fileName": "ryo_sticker_04_coffee.jpg",
    "title": "Стикер: 04 coffee",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_04_coffee.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_05_thinking_jpg",
    "fileName": "ryo_sticker_05_thinking.jpg",
    "title": "Стикер: 05 thinking",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_05_thinking.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_06_pout_jpg",
    "fileName": "ryo_sticker_06_pout.jpg",
    "title": "Стикер: 06 pout",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_06_pout.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_07_thumbsup_jpg",
    "fileName": "ryo_sticker_07_thumbsup.jpg",
    "title": "Стикер: 07 thumbsup",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_07_thumbsup.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_09_gaming_jpg",
    "fileName": "ryo_sticker_09_gaming.jpg",
    "title": "Стикер: 09 gaming",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_09_gaming.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_10_secret_jpg",
    "fileName": "ryo_sticker_10_secret.jpg",
    "title": "Стикер: 10 secret",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_10_secret.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_11_idk_exact_jpg",
    "fileName": "ryo_sticker_11_idk_exact.jpg",
    "title": "Стикер: 11 idk exact",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_11_idk_exact.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_11_shrug_jpg",
    "fileName": "ryo_sticker_11_shrug.jpg",
    "title": "Стикер: 11 shrug",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_11_shrug.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_12_whatever_jpg",
    "fileName": "ryo_sticker_12_whatever.jpg",
    "title": "Стикер: 12 whatever",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_12_whatever.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_12_whatever_exact_jpg",
    "fileName": "ryo_sticker_12_whatever_exact.jpg",
    "title": "Стикер: 12 whatever exact",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_12_whatever_exact.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_13_really_jpg",
    "fileName": "ryo_sticker_13_really.jpg",
    "title": "Стикер: 13 really",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_13_really.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_13_shock_o_exact_jpg",
    "fileName": "ryo_sticker_13_shock_o_exact.jpg",
    "title": "Стикер: 13 shock o exact",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_13_shock_o_exact.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_14_facepalm_jpg",
    "fileName": "ryo_sticker_14_facepalm.jpg",
    "title": "Стикер: 14 facepalm",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_14_facepalm.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_15_deadline_jpg",
    "fileName": "ryo_sticker_15_deadline.jpg",
    "title": "Стикер: 15 deadline",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_15_deadline.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_16_victory_jpg",
    "fileName": "ryo_sticker_16_victory.jpg",
    "title": "Стикер: 16 victory",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_16_victory.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_17_debug_jpg",
    "fileName": "ryo_sticker_17_debug.jpg",
    "title": "Стикер: 17 debug",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_17_debug.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_18_overload_jpg",
    "fileName": "ryo_sticker_18_overload.jpg",
    "title": "Стикер: 18 overload",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_18_overload.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_19_flowstate_jpg",
    "fileName": "ryo_sticker_19_flowstate.jpg",
    "title": "Стикер: 19 flowstate",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_19_flowstate.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_20_insight_jpg",
    "fileName": "ryo_sticker_20_insight.jpg",
    "title": "Стикер: 20 insight",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_20_insight.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_21_sarcasm_jpg",
    "fileName": "ryo_sticker_21_sarcasm.jpg",
    "title": "Стикер: 21 sarcasm",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_21_sarcasm.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_22_laughing_jpg",
    "fileName": "ryo_sticker_22_laughing.jpg",
    "title": "Стикер: 22 laughing",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_22_laughing.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_23_sprint_jpg",
    "fileName": "ryo_sticker_23_sprint.jpg",
    "title": "Стикер: 23 sprint",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_23_sprint.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_24_drained_jpg",
    "fileName": "ryo_sticker_24_drained.jpg",
    "title": "Стикер: 24 drained",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_24_drained.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_25_zen_freedom_1788360407663_jpg",
    "fileName": "ryo_sticker_25_zen_freedom_1788360407663.jpg",
    "title": "Стикер: 25 zen freedom",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_25_zen_freedom_1788360407663.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_25_zen_sensei_jpg",
    "fileName": "ryo_sticker_25_zen_sensei.jpg",
    "title": "Стикер: 25 zen sensei",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_25_zen_sensei.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_26_code_review_jpg",
    "fileName": "ryo_sticker_26_code_review.jpg",
    "title": "Стикер: 26 code review",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_26_code_review.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_27_what_bug_jpg",
    "fileName": "ryo_sticker_27_what_bug.jpg",
    "title": "Стикер: 27 what bug",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_27_what_bug.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_28_burnout_jpg",
    "fileName": "ryo_sticker_28_burnout.jpg",
    "title": "Стикер: 28 burnout",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_28_burnout.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_29_prod_on_fire_jpg",
    "fileName": "ryo_sticker_29_prod_on_fire.jpg",
    "title": "Стикер: 29 prod on fire",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_29_prod_on_fire.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_30_task_done_jpg",
    "fileName": "ryo_sticker_30_task_done.jpg",
    "title": "Стикер: 30 task done",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_30_task_done.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_lovestruck_side_droop_1788285419620_jpg",
    "fileName": "ryo_sticker_lovestruck_side_droop_1788285419620.jpg",
    "title": "Стикер: lovestruck side droop",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_lovestruck_side_droop_1788285419620.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_melting_fuzzy_cuteness_1788285783538_jpg",
    "fileName": "ryo_sticker_melting_fuzzy_cuteness_1788285783538.jpg",
    "title": "Стикер: melting fuzzy cuteness",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_melting_fuzzy_cuteness_1788285783538.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_side_lovestruck_melting_1788285846317_jpg",
    "fileName": "ryo_sticker_side_lovestruck_melting_1788285846317.jpg",
    "title": "Стикер: side lovestruck melting",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_side_lovestruck_melting_1788285846317.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_sticker_squish_exact_original_1788285720755_jpg",
    "fileName": "ryo_sticker_squish_exact_original_1788285720755.jpg",
    "title": "Стикер: squish exact original",
    "folderId": "stickers",
    "folderName": "Стикерпак MrDev",
    "src": "gallery/full/ryo_sticker_squish_exact_original_1788285720755.jpg",
    "badge": "Стикер",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_video_1_mp4",
    "fileName": "ryo_video_1.mp4",
    "title": "Video 1",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/ryo_video_1.mp4",
    "badge": "MP4 Video",
    "fileType": "video",
    "isFromFull": true
  },
  {
    "id": "ryo_yamada_art_1788265353920_jpg",
    "fileName": "ryo_yamada_art_1788265353920.jpg",
    "title": "Yamada art",
    "folderId": "artworks",
    "folderName": "Иллюстрации и арт",
    "src": "gallery/full/ryo_yamada_art_1788265353920.jpg",
    "badge": "JPG",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_ai_antigravity_1788361569300_jpg",
    "fileName": "ryo_yt_thumb_ai_antigravity_1788361569300.jpg",
    "title": "YouTube: ai antigravity",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_ai_antigravity_1788361569300.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_blank_page_syndrome_jpg",
    "fileName": "ryo_yt_thumb_blank_page_syndrome.jpg",
    "title": "YouTube: blank page syndrome",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_blank_page_syndrome.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_dark_aesthetic_jpg",
    "fileName": "ryo_yt_thumb_dark_aesthetic.jpg",
    "title": "YouTube: dark aesthetic",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_dark_aesthetic.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_lofi_cozy_1788360605909_jpg",
    "fileName": "ryo_yt_thumb_lofi_cozy_1788360605909.jpg",
    "title": "YouTube: lofi cozy",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_lofi_cozy_1788360605909.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_stack_2027_jpg",
    "fileName": "ryo_yt_thumb_stack_2027.jpg",
    "title": "YouTube: stack 2027",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_stack_2027.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_trio_branded_colors_fullstack_jpg",
    "fileName": "ryo_yt_thumb_trio_branded_colors_fullstack.jpg",
    "title": "YouTube: trio branded colors fullstack",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_trio_branded_colors_fullstack.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_trio_deadpan_fullstack_jpg",
    "fileName": "ryo_yt_thumb_trio_deadpan_fullstack.jpg",
    "title": "YouTube: trio deadpan fullstack",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_trio_deadpan_fullstack.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_vibe_coding_hardcore_jpg",
    "fileName": "ryo_yt_thumb_vibe_coding_hardcore.jpg",
    "title": "YouTube: vibe coding hardcore",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_vibe_coding_hardcore.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "ryo_yt_thumb_vibe_coding_truth_jpg",
    "fileName": "ryo_yt_thumb_vibe_coding_truth.jpg",
    "title": "YouTube: vibe coding truth",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/ryo_yt_thumb_vibe_coding_truth.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "youtube_thumbnail_it_jpg",
    "fileName": "youtube_thumbnail_it.jpg",
    "title": "Youtube thumbnail it",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/youtube_thumbnail_it.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "yt_thumb_trio_deadpan_1789388719219_jpg",
    "fileName": "yt_thumb_trio_deadpan_1789388719219.jpg",
    "title": "YouTube: trio deadpan",
    "folderId": "youtube",
    "folderName": "YouTube и Промо",
    "src": "gallery/full/yt_thumb_trio_deadpan_1789388719219.jpg",
    "badge": "YouTube",
    "fileType": "image",
    "isFromFull": true
  },
  {
    "id": "_____________________________mp4",
    "fileName": "черный_фон_простые_движения_.mp4",
    "title": "Черный фон простые движения",
    "folderId": "animations",
    "folderName": "Анимации и видео",
    "src": "gallery/full/%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D1%84%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%B5_%D0%B4%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F_.mp4",
    "badge": "MP4 Video",
    "fileType": "video",
    "isFromFull": true
  }
];

export const GALLERY_FOLDERS: GalleryFolder[] = [
  {
    id: 'all',
    name: 'Все материалы',
    description: 'Полная медиатека платформы: все арты, стикеры, баннеры и промо-материалы.',
    count: 117,
    previewSrc: 'gallery/how-to-enter-it-horizontal.jpg',
  },
  {
    id: 'full_folder',
    name: 'Папка: Фулл (Brand & Ryo)',
    description: 'Оригинальный архив: 111 файлов бренд-материалов, стикеров и концептов Ryo.',
    count: 111,
    previewSrc: 'gallery/full/ryo_clean_no_cyan.jpg',
  },
  {
    id: 'stickers',
    name: 'Стикерпак MrDev',
    description: '37 эмоций и стикеров персонажа Ryo для кодинга, дебага и реакций.',
    count: 37,
    previewSrc: 'gallery/full/ryo_sticker_01_wink_1788279355633.jpg',
  },
  {
    id: 'youtube',
    name: 'YouTube и Промо',
    description: 'Обложки видео, превью курсов и промо-постеры для соцсетей.',
    count: 14,
    previewSrc: 'gallery/how-to-enter-it-horizontal.jpg',
  },
  {
    id: 'poses',
    name: 'Позы и сцены Ryo',
    description: 'Концептуальные позы персонажа: размышления, кодинг-флоу и сцены.',
    count: 14,
    previewSrc: 'gallery/full/pose_1_coding_flow_1788265791557.jpg',
  },
  {
    id: 'brand',
    name: 'Бренд и концепты',
    description: 'Логотипы MrDEV, бизнес-модель, превью образовательной платформы.',
    count: 22,
    previewSrc: 'gallery/mrdev-bracket-logo.jpg',
  },
  {
    id: 'artworks',
    name: 'Иллюстрации и арт',
    description: 'Полноразмерные арт-иллюстрации и концепты маскота в темной эстетике.',
    count: 19,
    previewSrc: 'gallery/mrdev-mascot-portrait.jpg',
  },
  {
    id: 'animations',
    name: 'Анимации и видео',
    description: 'GIF-лупы, анимации движений и короткие видео-заставки.',
    count: 7,
    previewSrc: 'gallery/full/ryo_gif_1.gif',
  },
];
