import { ProjectShowcase } from './types';

export const DEFAULT_STUDENT_PROJECTS: ProjectShowcase[] = [
  {
    id: 1,
    userId: 101,
    title: 'Таңда (Tanda) — Платформа аудио и электронных книг',
    description:
      'Полноценный запущенный коммерческий веб-сервис на собственном домене: қазақ тіліндегі аудиокітаптар мен электронды кітаптар платформасы. PWA, онлайн-оқу, аудио-плеер, 100+ кітап.',
    liveDemoUrl: 'https://tandamen.kz/',
    githubRepoUrl: 'https://github.com/usmansulaimanov',
    authorName: 'Усман Сулейманов',
    authorAvatarUrl: 'https://github.com/usmansulaimanov.png',
    techStack: 'React, TypeScript, PWA, Audio Stream, SEO',
    featured: true,
    likesCount: 14,
    createdAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 2,
    userId: 102,
    title: 'QazaqMarket — Онлайн маркетплейс книг',
    description:
      'Казахстанский маркетплейс книг с рубрикатором, корзиной, умной фильтрацией и быстрым оформлением заказов.',
    liveDemoUrl: 'https://rmekenov-pixel.github.io/test-marketplace/',
    githubRepoUrl: 'https://github.com/rmekenov-pixel/test-marketplace',
    authorName: 'Ратмир Мекенов',
    authorAvatarUrl: 'https://github.com/rmekenov-pixel.png',
    techStack: 'React 19, Vite, TypeScript, Tailwind CSS',
    featured: true,
    likesCount: 9,
    createdAt: '2026-09-02T14:30:00Z',
  },
  {
    id: 3,
    userId: 101,
    title: 'KitapAll — Заманауи киім және кітап маркетплейсі',
    description:
      'Маркетплейс с каталогом товаров, переключением темной/светлой темы, интерактивной корзиной и адаптивным интерфейсом.',
    liveDemoUrl: 'https://usmansulaimanov.github.io/test_marketplace/#/',
    githubRepoUrl: 'https://github.com/usmansulaimanov/test_marketplace',
    authorName: 'Усман Сулейманов',
    authorAvatarUrl: 'https://github.com/usmansulaimanov.png',
    techStack: 'React 19, Vite, TypeScript, Tailwind CSS',
    featured: false,
    likesCount: 7,
    createdAt: '2026-09-03T10:15:00Z',
  },
  {
    id: 4,
    userId: 101,
    title: 'Global Coffee — Сеть кофеен',
    description:
      'Презентационный лендинг сети кофеен в Шымкенте и на юге Казахстана с эстетичным Glassmorphism-дизайном, меню и картой локаций.',
    liveDemoUrl: 'https://usmansulaimanov.github.io/landing/',
    githubRepoUrl: 'https://github.com/usmansulaimanov/landing',
    authorName: 'Усман Сулейманов',
    authorAvatarUrl: 'https://github.com/usmansulaimanov.png',
    techStack: 'HTML5, CSS3, JavaScript, Glassmorphism',
    featured: false,
    likesCount: 5,
    createdAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 5,
    userId: 102,
    title: 'Digital Projects Hub — Spotify & MindCheck',
    description:
      'Портал цифровых сервисов с интерактивным музыкальным плеером Spotify и психологическим трекером MindCheck.',
    liveDemoUrl: 'https://rmekenov-pixel.github.io/landing/',
    githubRepoUrl: 'https://github.com/rmekenov-pixel/landing',
    authorName: 'Ратмир Мекенов',
    authorAvatarUrl: 'https://github.com/rmekenov-pixel.png',
    techStack: 'HTML5, CSS3, JavaScript, Spotify API',
    featured: false,
    likesCount: 6,
    createdAt: '2026-09-05T09:45:00Z',
  },
];
