export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: (slug: string) => `/courses/${slug}`,
  LESSON: (courseId: number | string, lessonId: number | string) => `/courses/${courseId}/lessons/${lessonId}`,
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  PROJECTS: '/projects',
  LOGIN: '/login',
  ADMIN: '/admin',
  DOCS: '/docs',
  GLOSSARY: '/glossary',
  CERTIFICATES_VERIFY: '/certificates/verify',
  AUTH_CALLBACK: '/auth/callback',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const;
